import type { Transaction, AppNotification, RequestDetails } from "./types";

const emptyDetails: RequestDetails = {
  lcNumber: "",
  dateOfIssue: "",
  currency: "USD",
  amount: 0,
  lcType: "AT_SIGHT",
  tenorOfDraft: "",
  confirmationInstruction: "NOT_REQUIRED",
  applicantName: "",
  applicantAddress: "",
  beneficiaryName: "",
  beneficiaryAddress: "",
  goodsDescription: "",
  hsCode: "",
  countryOfOrigin: "",
  portOfLoading: "",
  portOfDischarge: "",
  latestShipmentDate: "",
  expiryDate: "",
  placeOfExpiry: "",
  advisingBank: "",
  presentationPeriod: "21 days",
  chargesBorneBy: "Applicant's account",
  beneficiaryPaymentNote: "",
  remarks: "",
  lcCopyFileName: "",
};

export function blankDetails(): RequestDetails {
  return { ...emptyDetails };
}

export function seedTransactions(): Transaction[] {
  return [
    {
      id: "txn-1001",
      referenceNo: "TRTD-2026-001001",
      requestType: "ADD_CONF_DISC",
      status: "PRICE_OFFERED",
      createdAt: "2026-08-05T04:20:00.000Z",
      updatedAt: "2026-08-06T09:10:00.000Z",
      raisedByName: "Rakib Hasan (RM)",
      branch: "Khatungonj Branch, Chattogram",
      details: {
        ...emptyDetails,
        lcNumber: "MTBL/IMP/2026/48960",
        dateOfIssue: "2026-08-04",
        currency: "USD",
        amount: 489600,
        lcType: "UPAS",
        tenorOfDraft:
          "180 days from the date of B/L, acceptance & negotiation. Up to 60 days supplier's credit; from 61st day to 180 days buyer's credit or UPAS.",
        confirmationInstruction: "REQUIRED",
        applicantName: "BENGAL SACK CORPORATION LTD. (a sister concern of T.K. Group)",
        applicantAddress: "83, Khatungonj, Chattogram, Bangladesh",
        beneficiaryName: "SABIC ASIA PACIFIC PTE LTD.",
        beneficiaryAddress: "One Temasek Avenue #06-01, Millenia Tower, Singapore",
        goodsDescription: "POLYPROPYLENE",
        hsCode: "3902.10.00",
        countryOfOrigin: "Saudi Arabia / Malaysia / Korea",
        portOfLoading: "Saudi Arabia / Malaysia / Singapore",
        portOfDischarge: "Chittagong Sea Port, Bangladesh",
        latestShipmentDate: "2026-08-31",
        expiryDate: "2026-09-21",
        placeOfExpiry: "Singapore",
        advisingBank: "Standard Chartered Bank, Singapore",
        presentationPeriod: "21 days",
        chargesBorneBy:
          "Confirmation & discounting charges are on applicant's account",
        beneficiaryPaymentNote:
          "Beneficiary will get payment on the 61st day from the date of shipment by the discounting bank.",
        remarks: "If you accept our request, please quote your price by return.",
        lcCopyFileName: "LC-Draft-489600.pdf",
      },
      quotes: [
        {
          quotedAt: "2026-08-06T09:10:00.000Z",
          quotedBy: "Tanvir Ahmed (MFIS)",
          revision: 1,
          confirmationRate: "2.40",
          confirmationBasis:
            "p.a. on LC value (including tolerance, if any) from the date of confirmation till financing",
          confirmationMinCharge: "USD 500",
          financingBaseRate: "SOFR",
          financingMargin: "2.40",
          financingBasis:
            "p.a. on draft value from the date of financing till payment maturity",
          financingMinCharge: "USD 500",
          issuingToBank:
            "LC to be issued to SCB-Singapore; documents to be presented at SCB-Singapore counter",
          maxDoorToDoorTenorDays: "360",
          maxSingleLcValue: "USD 3 Mn",
          reimbursementBank: "SCB, New York",
          includeInMt700: true,
          subjectToCreditApproval: true,
          validityDays: "7",
          validUntil: "2026-08-13",
          additionalConditions:
            "Discounting/financing must be completed within the validity period. Otherwise financing execution will be subject to limit availability and the rate will be determined on the basis of the prevailing rate on the financing date.",
        },
      ],
      forwards: [
        {
          forwardedAt: "2026-08-05T10:00:00.000Z",
          forwardedTo: "Standard Chartered Bank, Singapore",
          channel: "THIRD_BANK",
          note: "Requested indicative confirmation and discounting pricing.",
          responseAt: "2026-08-06T06:30:00.000Z",
          responseSummary:
            "Able to accommodate subject to internal credit approval and due diligence.",
          indicativePricing: "Confirmation 2.40% p.a.; Financing SOFR + 2.40% p.a.",
        },
      ],
      queries: [],
      history: [
        {
          id: "h1",
          at: "2026-08-05T04:20:00.000Z",
          actorName: "Rakib Hasan (RM)",
          actorRole: "RM",
          action: "Request submitted to MFIS",
          statusAfter: "SUBMITTED",
        },
        {
          id: "h2",
          at: "2026-08-05T10:00:00.000Z",
          actorName: "Tanvir Ahmed (MFIS)",
          actorRole: "MFIS",
          action: "Forwarded to Standard Chartered Bank, Singapore",
          statusAfter: "FORWARDED",
        },
        {
          id: "h3",
          at: "2026-08-06T06:30:00.000Z",
          actorName: "Tanvir Ahmed (MFIS)",
          actorRole: "MFIS",
          action: "Third bank response recorded",
          statusAfter: "FORWARDED",
        },
        {
          id: "h4",
          at: "2026-08-06T09:10:00.000Z",
          actorName: "Tanvir Ahmed (MFIS)",
          actorRole: "MFIS",
          action: "Price quote offered (revision 1)",
          statusAfter: "PRICE_OFFERED",
        },
      ],
    },
    {
      id: "txn-1002",
      referenceNo: "TRTD-2026-001002",
      requestType: "DISCOUNTING",
      status: "SUBMITTED",
      createdAt: "2026-08-10T05:05:00.000Z",
      updatedAt: "2026-08-10T05:05:00.000Z",
      raisedByName: "Rakib Hasan (RM)",
      branch: "Gazipur Branch",
      details: {
        ...emptyDetails,
        lcNumber: "MTBL/IMP/2026/11500",
        dateOfIssue: "2026-08-09",
        currency: "USD",
        amount: 115000,
        lcType: "UPAS",
        tenorOfDraft:
          "360 days from the date of acceptance, but beneficiary will get payment at sight.",
        confirmationInstruction: "NOT_REQUIRED",
        applicantName: "ALTECH ALUMINIUM INDUSTRIES LIMITED",
        applicantAddress: "417, Bhurulia, Gazipur, Bangladesh",
        beneficiaryName: "PANMARK IMPEX PTE LIMITED",
        beneficiaryAddress: "Golden Wall Flatted Factory, Singapore",
        goodsDescription: "BRAND NEW AIR COOLED VRV",
        hsCode: "8415.10.10",
        countryOfOrigin: "Thailand / Japan",
        portOfLoading: "Any port of Thailand",
        portOfDischarge: "Chattogram, Bangladesh",
        latestShipmentDate: "2026-09-20",
        expiryDate: "2026-10-11",
        placeOfExpiry: "Singapore",
        advisingBank: "HSBC Singapore",
        presentationPeriod: "21 days",
        chargesBorneBy: "Applicant's account",
        beneficiaryPaymentNote: "Beneficiary will get payment at sight.",
        remarks: "Please quote your price by return.",
        lcCopyFileName: "LC-115000.pdf",
      },
      quotes: [],
      forwards: [],
      queries: [],
      history: [
        {
          id: "h1",
          at: "2026-08-10T05:05:00.000Z",
          actorName: "Rakib Hasan (RM)",
          actorRole: "RM",
          action: "Request submitted to MFIS",
          statusAfter: "SUBMITTED",
        },
      ],
    },
    {
      id: "txn-1003",
      referenceNo: "TRTD-2026-001003",
      requestType: "CONFIRMATION",
      status: "QUERY_RAISED",
      createdAt: "2026-08-08T06:00:00.000Z",
      updatedAt: "2026-08-09T07:30:00.000Z",
      raisedByName: "Nusrat Jahan (RM)",
      branch: "Motijheel Branch, Dhaka",
      details: {
        ...emptyDetails,
        lcNumber: "MTBL/IMP/2026/22045",
        dateOfIssue: "2026-08-07",
        currency: "USD",
        amount: 220450,
        lcType: "AT_SIGHT",
        tenorOfDraft: "At sight",
        confirmationInstruction: "REQUIRED",
        applicantName: "NORTHERN TEXTILES LTD.",
        applicantAddress: "Motijheel C/A, Dhaka, Bangladesh",
        beneficiaryName: "TEXCHEM TRADING LTD.",
        beneficiaryAddress: "Kowloon, Hong Kong",
        goodsDescription: "COTTON YARN 30/1",
        hsCode: "5205.23.00",
        countryOfOrigin: "China",
        portOfLoading: "Any Chinese port",
        portOfDischarge: "Chattogram, Bangladesh",
        latestShipmentDate: "2026-09-15",
        expiryDate: "2026-10-05",
        placeOfExpiry: "Hong Kong",
        advisingBank: "Standard Chartered Bank, Hong Kong",
        chargesBorneBy: "Applicant's account",
        remarks: "Confirmation required at the earliest.",
      },
      quotes: [],
      forwards: [],
      queries: [
        {
          id: "q1",
          subject: "LC copy and tolerance clause",
          raisedAt: "2026-08-09T07:30:00.000Z",
          raisedByRole: "MFIS",
          messages: [
            {
              id: "qm1",
              at: "2026-08-09T07:30:00.000Z",
              byName: "Tanvir Ahmed (MFIS)",
              byRole: "MFIS",
              message:
                "Please share the LC copy and confirm whether a tolerance clause applies to the LC value.",
            },
          ],
        },
      ],
      history: [
        {
          id: "h1",
          at: "2026-08-08T06:00:00.000Z",
          actorName: "Nusrat Jahan (RM)",
          actorRole: "RM",
          action: "Request submitted to MFIS",
          statusAfter: "SUBMITTED",
        },
        {
          id: "h2",
          at: "2026-08-09T07:30:00.000Z",
          actorName: "Tanvir Ahmed (MFIS)",
          actorRole: "MFIS",
          action: "Query raised to RM",
          remarks: "LC copy and tolerance clause",
          statusAfter: "QUERY_RAISED",
        },
      ],
    },
    {
      id: "txn-1004",
      referenceNo: "TRTD-2026-001004",
      requestType: "ADD_CONF_DISC",
      status: "ACCEPTED",
      createdAt: "2026-07-28T04:00:00.000Z",
      updatedAt: "2026-08-11T05:00:00.000Z",
      raisedByName: "Rakib Hasan (RM)",
      branch: "Dilkusha Corporate Branch",
      details: {
        ...emptyDetails,
        lcNumber: "MTBL/IMP/2026/75300",
        dateOfIssue: "2026-07-27",
        currency: "USD",
        amount: 753000,
        lcType: "DEFERRED",
        tenorOfDraft: "120 days from the date of B/L",
        confirmationInstruction: "REQUIRED",
        applicantName: "META STEEL INDUSTRIES LTD.",
        applicantAddress: "Dilkusha C/A, Dhaka, Bangladesh",
        beneficiaryName: "GLOBAL METALS DMCC",
        beneficiaryAddress: "Jumeirah Lakes Towers, Dubai, UAE",
        goodsDescription: "HOT ROLLED STEEL COILS",
        hsCode: "7208.39.00",
        countryOfOrigin: "UAE / India",
        portOfLoading: "Jebel Ali",
        portOfDischarge: "Chattogram, Bangladesh",
        latestShipmentDate: "2026-09-05",
        expiryDate: "2026-09-26",
        placeOfExpiry: "Dubai",
        advisingBank: "Mashreq Bank, Dubai",
        chargesBorneBy: "Applicant's account",
      },
      quotes: [
        {
          quotedAt: "2026-08-02T08:00:00.000Z",
          quotedBy: "Tanvir Ahmed (MFIS)",
          revision: 1,
          confirmationRate: "2.10",
          confirmationBasis: "p.a. on LC value from confirmation till financing",
          confirmationMinCharge: "USD 500",
          financingBaseRate: "SOFR",
          financingMargin: "2.75",
          financingBasis: "p.a. on draft value from financing till payment maturity",
          financingMinCharge: "USD 500",
          issuingToBank: "LC to be issued to SCB-Singapore",
          maxDoorToDoorTenorDays: "360",
          maxSingleLcValue: "USD 3 Mn",
          reimbursementBank: "SCB, New York",
          includeInMt700: true,
          subjectToCreditApproval: true,
          validityDays: "7",
          validUntil: "2026-08-09",
          additionalConditions: "",
        },
        {
          quotedAt: "2026-08-10T10:30:00.000Z",
          quotedBy: "Tanvir Ahmed (MFIS)",
          revision: 2,
          confirmationRate: "2.00",
          confirmationBasis: "p.a. on LC value from confirmation till financing",
          confirmationMinCharge: "USD 500",
          financingBaseRate: "SOFR",
          financingMargin: "2.50",
          financingBasis: "p.a. on draft value from financing till payment maturity",
          financingMinCharge: "USD 500",
          issuingToBank: "LC to be issued to SCB-Singapore",
          maxDoorToDoorTenorDays: "360",
          maxSingleLcValue: "USD 3 Mn",
          reimbursementBank: "SCB, New York",
          includeInMt700: true,
          subjectToCreditApproval: true,
          validityDays: "7",
          validUntil: "2026-08-17",
          additionalConditions: "Revised pricing after client negotiation.",
        },
      ],
      forwards: [],
      queries: [],
      history: [
        {
          id: "h1",
          at: "2026-07-28T04:00:00.000Z",
          actorName: "Rakib Hasan (RM)",
          actorRole: "RM",
          action: "Request submitted to MFIS",
          statusAfter: "SUBMITTED",
        },
        {
          id: "h2",
          at: "2026-08-02T08:00:00.000Z",
          actorName: "Tanvir Ahmed (MFIS)",
          actorRole: "MFIS",
          action: "Price quote offered (revision 1)",
          statusAfter: "PRICE_OFFERED",
        },
        {
          id: "h3",
          at: "2026-08-09T09:00:00.000Z",
          actorName: "Rakib Hasan (RM)",
          actorRole: "RM",
          action: "Price rejected",
          remarks: "Client finds the financing margin high.",
          statusAfter: "REJECTED_BY_RM",
        },
        {
          id: "h4",
          at: "2026-08-10T10:30:00.000Z",
          actorName: "Tanvir Ahmed (MFIS)",
          actorRole: "MFIS",
          action: "Revised price quote offered (revision 2)",
          statusAfter: "PRICE_OFFERED",
        },
        {
          id: "h5",
          at: "2026-08-11T05:00:00.000Z",
          actorName: "Rakib Hasan (RM)",
          actorRole: "RM",
          action: "Price accepted — routed to MITS for execution",
          statusAfter: "ACCEPTED",
        },
      ],
    },
    {
      id: "txn-1005",
      referenceNo: "TRTD-2026-001005",
      requestType: "DISCOUNTING",
      status: "COMPLETED",
      createdAt: "2026-07-10T04:00:00.000Z",
      updatedAt: "2026-07-20T11:00:00.000Z",
      raisedByName: "Nusrat Jahan (RM)",
      branch: "Agrabad Branch, Chattogram",
      details: {
        ...emptyDetails,
        lcNumber: "MTBL/IMP/2026/09820",
        dateOfIssue: "2026-07-09",
        currency: "USD",
        amount: 98200,
        lcType: "UPAS",
        tenorOfDraft: "270 days from the date of acceptance; beneficiary paid at sight",
        confirmationInstruction: "NOT_REQUIRED",
        applicantName: "SOUTHERN FOODS LTD.",
        applicantAddress: "Agrabad C/A, Chattogram, Bangladesh",
        beneficiaryName: "ASIA COMMODITIES PTE LTD.",
        beneficiaryAddress: "Raffles Place, Singapore",
        goodsDescription: "REFINED PALM OIL",
        hsCode: "1511.90.00",
        countryOfOrigin: "Malaysia",
        portOfLoading: "Port Klang",
        portOfDischarge: "Chattogram, Bangladesh",
        latestShipmentDate: "2026-08-10",
        expiryDate: "2026-08-31",
        placeOfExpiry: "Singapore",
        advisingBank: "DBS Bank, Singapore",
        chargesBorneBy: "Applicant's account",
      },
      quotes: [
        {
          quotedAt: "2026-07-14T07:00:00.000Z",
          quotedBy: "Tanvir Ahmed (MFIS)",
          revision: 1,
          confirmationRate: "",
          confirmationBasis: "",
          confirmationMinCharge: "",
          financingBaseRate: "SOFR",
          financingMargin: "3.00",
          financingBasis: "p.a. on draft value from financing till payment maturity",
          financingMinCharge: "USD 500",
          issuingToBank: "LC to be issued to SCB-Singapore",
          maxDoorToDoorTenorDays: "360",
          maxSingleLcValue: "USD 3 Mn",
          reimbursementBank: "SCB, New York",
          includeInMt700: true,
          subjectToCreditApproval: true,
          validityDays: "7",
          validUntil: "2026-07-21",
          additionalConditions: "",
        },
      ],
      forwards: [],
      queries: [],
      execution: {
        executedAt: "2026-07-18T09:00:00.000Z",
        executedBy: "Sabbir Rahman (MITS)",
        referenceNo: "MT700/2026/09820",
        remarks: "LC issued with pricing included in field 47A.",
        completedAt: "2026-07-20T11:00:00.000Z",
      },
      history: [
        {
          id: "h1",
          at: "2026-07-10T04:00:00.000Z",
          actorName: "Nusrat Jahan (RM)",
          actorRole: "RM",
          action: "Request submitted to MFIS",
          statusAfter: "SUBMITTED",
        },
        {
          id: "h2",
          at: "2026-07-14T07:00:00.000Z",
          actorName: "Tanvir Ahmed (MFIS)",
          actorRole: "MFIS",
          action: "Price quote offered (revision 1)",
          statusAfter: "PRICE_OFFERED",
        },
        {
          id: "h3",
          at: "2026-07-15T05:00:00.000Z",
          actorName: "Nusrat Jahan (RM)",
          actorRole: "RM",
          action: "Price accepted — routed to MITS for execution",
          statusAfter: "ACCEPTED",
        },
        {
          id: "h4",
          at: "2026-07-18T09:00:00.000Z",
          actorName: "Sabbir Rahman (MITS)",
          actorRole: "MITS",
          action: "Transaction executed",
          remarks: "MT700/2026/09820",
          statusAfter: "EXECUTED",
        },
        {
          id: "h5",
          at: "2026-07-20T11:00:00.000Z",
          actorName: "Sabbir Rahman (MITS)",
          actorRole: "MITS",
          action: "Transaction completed",
          statusAfter: "COMPLETED",
        },
      ],
    },
  ];
}

export function seedNotifications(): AppNotification[] {
  return [
    {
      id: "n1",
      at: "2026-08-06T09:10:00.000Z",
      toRole: "RM",
      transactionId: "txn-1001",
      referenceNo: "TRTD-2026-001001",
      title: "Price offered",
      body: "MFIS has quoted pricing for USD 489,600.00 add confirmation & discounting request.",
      read: false,
      emailTo: "rm.khatungonj@mtb.com.bd",
    },
    {
      id: "n2",
      at: "2026-08-10T05:05:00.000Z",
      toRole: "MFIS",
      transactionId: "txn-1002",
      referenceNo: "TRTD-2026-001002",
      title: "New discounting request",
      body: "RM submitted a discounting request for USD 115,000.00.",
      read: false,
      emailTo: "mfis@mtb.com.bd",
    },
    {
      id: "n3",
      at: "2026-08-11T05:00:00.000Z",
      toRole: "MITS",
      transactionId: "txn-1004",
      referenceNo: "TRTD-2026-001004",
      title: "Transaction ready for execution",
      body: "RM accepted the price for USD 753,000.00. Please execute.",
      read: false,
      emailTo: "mits@mtb.com.bd",
    },
  ];
}
