/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ExportFormRouteImport } from './routes/export.$form'
import { Route as GuaranteeFormRouteImport } from './routes/guarantee.$form'
import { Route as ImportNonDesignatedRouteImport } from './routes/import.non-designated'
import { Route as ImportOtherBankRouteImport } from './routes/import.other-bank'
import { Route as RequestsIndexRouteImport } from './routes/requests.index'
import { Route as RequestsIdRouteImport } from './routes/requests.$id'
import { Route as RequestsNewRouteImport } from './routes/requests.new'
import { Route as ImportMtbFormRouteImport } from './routes/import.mtb.$form'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportFormRoute = ExportFormRouteImport.update({
  id: '/export/$form',
  path: '/export/$form',
  getParentRoute: () => rootRouteImport,
} as any)
const GuaranteeFormRoute = GuaranteeFormRouteImport.update({
  id: '/guarantee/$form',
  path: '/guarantee/$form',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportNonDesignatedRoute = ImportNonDesignatedRouteImport.update({
  id: '/import/non-designated',
  path: '/import/non-designated',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportOtherBankRoute = ImportOtherBankRouteImport.update({
  id: '/import/other-bank',
  path: '/import/other-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdRoute = RequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsNewRoute = RequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportMtbFormRoute = ImportMtbFormRouteImport.update({
  id: '/import/mtb/$form',
  path: '/import/mtb/$form',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/reports': typeof ReportsRoute
  '/export/$form': typeof ExportFormRoute
  '/guarantee/$form': typeof GuaranteeFormRoute
  '/import/non-designated': typeof ImportNonDesignatedRoute
  '/import/other-bank': typeof ImportOtherBankRoute
  '/requests/$id': typeof RequestsIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/requests/': typeof RequestsIndexRoute
  '/import/mtb/$form': typeof ImportMtbFormRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/reports': typeof ReportsRoute
  '/export/$form': typeof ExportFormRoute
  '/guarantee/$form': typeof GuaranteeFormRoute
  '/import/non-designated': typeof ImportNonDesignatedRoute
  '/import/other-bank': typeof ImportOtherBankRoute
  '/requests/$id': typeof RequestsIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/requests': typeof RequestsIndexRoute
  '/import/mtb/$form': typeof ImportMtbFormRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/reports': typeof ReportsRoute
  '/export/$form': typeof ExportFormRoute
  '/guarantee/$form': typeof GuaranteeFormRoute
  '/import/non-designated': typeof ImportNonDesignatedRoute
  '/import/other-bank': typeof ImportOtherBankRoute
  '/requests/$id': typeof RequestsIdRoute
  '/requests/new': typeof RequestsNewRoute
  '/requests/': typeof RequestsIndexRoute
  '/import/mtb/$form': typeof ImportMtbFormRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/notifications'
    | '/reports'
    | '/export/$form'
    | '/guarantee/$form'
    | '/import/non-designated'
    | '/import/other-bank'
    | '/requests/$id'
    | '/requests/new'
    | '/requests/'
    | '/import/mtb/$form'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/notifications'
    | '/reports'
    | '/export/$form'
    | '/guarantee/$form'
    | '/import/non-designated'
    | '/import/other-bank'
    | '/requests/$id'
    | '/requests/new'
    | '/requests'
    | '/import/mtb/$form'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/notifications'
    | '/reports'
    | '/export/$form'
    | '/guarantee/$form'
    | '/import/non-designated'
    | '/import/other-bank'
    | '/requests/$id'
    | '/requests/new'
    | '/requests/'
    | '/import/mtb/$form'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ReportsRoute: typeof ReportsRoute
  ExportFormRoute: typeof ExportFormRoute
  GuaranteeFormRoute: typeof GuaranteeFormRoute
  ImportNonDesignatedRoute: typeof ImportNonDesignatedRoute
  ImportOtherBankRoute: typeof ImportOtherBankRoute
  RequestsIdRoute: typeof RequestsIdRoute
  RequestsNewRoute: typeof RequestsNewRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
  ImportMtbFormRoute: typeof ImportMtbFormRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export/$form': {
      id: '/export/$form'
      path: '/export/$form'
      fullPath: '/export/$form'
      preLoaderRoute: typeof ExportFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guarantee/$form': {
      id: '/guarantee/$form'
      path: '/guarantee/$form'
      fullPath: '/guarantee/$form'
      preLoaderRoute: typeof GuaranteeFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import/non-designated': {
      id: '/import/non-designated'
      path: '/import/non-designated'
      fullPath: '/import/non-designated'
      preLoaderRoute: typeof ImportNonDesignatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import/other-bank': {
      id: '/import/other-bank'
      path: '/import/other-bank'
      fullPath: '/import/other-bank'
      preLoaderRoute: typeof ImportOtherBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id': {
      id: '/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof RequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/new': {
      id: '/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof RequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import/mtb/$form': {
      id: '/import/mtb/$form'
      path: '/import/mtb/$form'
      fullPath: '/import/mtb/$form'
      preLoaderRoute: typeof ImportMtbFormRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ReportsRoute: ReportsRoute,
  ExportFormRoute: ExportFormRoute,
  GuaranteeFormRoute: GuaranteeFormRoute,
  ImportNonDesignatedRoute: ImportNonDesignatedRoute,
  ImportOtherBankRoute: ImportOtherBankRoute,
  RequestsIdRoute: RequestsIdRoute,
  RequestsNewRoute: RequestsNewRoute,
  RequestsIndexRoute: RequestsIndexRoute,
  ImportMtbFormRoute: ImportMtbFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
